### ISSUE TITLE
Notification - Icons Redesigns

### ISSUE THREAD

**Issue by tonysaad** [wholesale-design-system/components#11]
We got updates for the icons
<img width="675" alt="screen shot 2017-03-03 at 16 56 29" src="https://cloud.githubusercontent.com/assets/1137569/23610479/f4d39f94-0272-11e7-9bcf-cc198078cd12.png">

**Comment by schluchter** [comment]
Hi @tonysaad, need any input from @wholesale-design-system/ux ?

**Comment by tonysaad** [comment]
This was just for testing in our session, but I remember that there was a new icons list Mehmet showed to us. Maybe let's start working on them using the new workflow.

**Comment by fokusferit** [comment]
@tonysaad still an issue ?

**Comment by tonysaad** [comment]
I'd close it to avoid confusion
