### ISSUE TITLE
DS Colors +1 gradient color

### ISSUE THREAD

**Issue by myueksel** [wholesale-design-system/components#14]
Added a gradient color as background for table headers.

https://zalando.invisionapp.com/d/main#/console/10454474/223408083/preview

![20170314_colors_ v2_my](https://cloud.githubusercontent.com/assets/25901307/23896299/2a7267ac-08a9-11e7-961c-e5b08e9bc3fe.png)

**Comment by fragsalat** [comment]
I will do that together with the spacings

**Comment by fokusferit** [comment]
@fragsalat still up-to-date? Otherwise just close.
