### ISSUE TITLE
Paper shadows and elevation

### ISSUE THREAD

**Issue by myueksel** [wholesale-design-system/components#15]
Specifications of Paper elements.

https://zalando.invisionapp.com/d/main#/console/10454474/225718499/preview

![paper elements v2](https://cloud.githubusercontent.com/assets/25901307/24351693/08badbb0-12e7-11e7-85f2-a00ac10037c0.png)

**Comment by schluchter** [comment]
Add blur value to make pop-over arrow tip visible again

**Comment by schluchter** [comment]
Elevation for popovers (paper-shadow-6) has been added in #32. Closing and removing from project.
