### ISSUE TITLE
Check boxes, option fields & switches

### ISSUE THREAD

**Issue by myueksel** [wholesale-design-system/components#18]
Check boxes, option fields & switches with all specifications.
https://zalando.invisionapp.com/d/main#/console/10454474/222964295/preview

![20170314_check_ v1_my](https://cloud.githubusercontent.com/assets/25901307/23899874/3efe51be-08b7-11e7-87b1-5d3e8705b0f0.png)

**Comment by fragsalat** [comment]
Is the checkmark icon available from the icon font?

**Comment by schluchter** [comment]
@fragsalat I will add it.

**Comment by fragsalat** [comment]
Thx :)

**Comment by schluchter** [comment]
@myueksel Please add specs for switch label positioning

**Comment by myueksel** [comment]
https://zalando.invisionapp.com/d/main#/console/10454474/227050843/preview

![check v3](https://cloud.githubusercontent.com/assets/25901307/24616219/c243ba1c-1890-11e7-97ac-fc71b4c3434f.png)

**Comment by fragsalat** [comment]
Did that here https://github.com/wholesale-design-system/scss/pull/43

Check out new style at https://wholesale-design-system.github.io/styleguide/#/elements/forms
