### ISSUE TITLE
Drop down menu solutions

### ISSUE THREAD

**Issue by myueksel** [wholesale-design-system/components#20]
All drop down solutions aligned to the new spacings.
https://zalando.invisionapp.com/d/main#/console/10454474/222956355/preview

![20170314_dropdown-solutions_ v2_my](https://cloud.githubusercontent.com/assets/25901307/23900224/a07743d2-08b8-11e7-8b55-6772e081b87c.png)

**Comment by myueksel** [comment]
new shadow added.

https://zalando.invisionapp.com/d/main#/console/10454474/227055833/preview

![drop downs v3](https://cloud.githubusercontent.com/assets/25901307/24616292/f5c87d46-1890-11e7-97e1-077c216c278e.png)

**Comment by fragsalat** [comment]
I did the most here already
Missing is:
- General solution for localization of components (Choose/Auswählen is currently just OK^^)
- There was no use case yet for items with icons before so that might need some adjustements
- Documentation in the styleguide page

**Comment by fokusferit** [comment]
@myueksel @fragsalat 
I'm closing this for now. 
- As we documented the dropdown thing
- Localization should be a dedicated topic
- if there is a need for icons, new issue / task.
