### ISSUE TITLE
Tabel filter panels 

### ISSUE THREAD

**Issue by myueksel** [wholesale-design-system/components#21]
Filter panels aligned to new spacings

https://zalando.invisionapp.com/d/main#/console/10454474/222960998/preview

![20170314_table-filter-panels _ v4_my](https://cloud.githubusercontent.com/assets/25901307/23900469/c3b96b62-08b9-11e7-92a4-a365b295a04a.png)

**Comment by myueksel** [comment]
panel color white again and new shadow added.

https://zalando.invisionapp.com/d/main#/console/10454474/227055588/preview

![table filter panels v5](https://cloud.githubusercontent.com/assets/25901307/24616341/1c434140-1891-11e7-84e9-2cb1e2a5212e.png)

**Comment by fragsalat** [comment]
I did most of this already
Missing is:
- Styling for "Reset all"
- Bottom spacing of badge has to be adjusted

**Comment by myueksel** [comment]
• Bottom spacing: 0,5rem (8px)
• Styling for "RESET ALL"....:
<img width="655" alt="screen shot 2017-05-16 at 11 54 53" src="https://cloud.githubusercontent.com/assets/25901307/26100860/6a1ef890-3a2f-11e7-85ca-e28071a776e6.png">

**Comment by schluchter** [comment]
Implemented in Block Order @myueksel Please check there!

**Comment by fokusferit** [comment]
@myueksel @schluchter what is the current state here? 

If it is done, please close.

**Comment by myueksel** [comment]
lets close it for now... because we have to overthink the whole filtering issue... regarding to the new table design.

Thank you.
