### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by myueksel** [wholesale-design-system/components#22]
Notifications aligned to new spacings.
https://zalando.invisionapp.com/d/main#/console/10454474/222960998/preview

![20170314_notifications_ v1_my](https://cloud.githubusercontent.com/assets/25901307/23900571/1d5ee5a2-08ba-11e7-8686-68514779357e.png)

**Comment by tonysaad** [comment]
Fixed in #38 #11

**Comment by fokusferit** [comment]
@tonysaad you documented them / is it done ? if yes could you please close the issue :) ?

**Comment by tonysaad** [comment]
@fokusferit Yeah Thomas documented them already, I'd close it now
