### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by myueksel** [wholesale-design-system/components#23]
aligned the date picker to the new spacings...
https://zalando.invisionapp.com/d/main#/console/10454474/223650900/preview

![20170315_date-picker_ v1_my](https://cloud.githubusercontent.com/assets/25901307/23944270/828cfb0e-0972-11e7-8549-9d8a97e43fc8.png)

**Comment by fragsalat** [comment]
:+1:

**Comment by myueksel** [comment]
Update... changed the fonts of the dates and the background color of the current day.
https://zalando.invisionapp.com/d/main#/console/10454474/227056253/preview

![date picker v2](https://cloud.githubusercontent.com/assets/25901307/24616563/ccf58a34-1891-11e7-8b59-f9e22e533bdd.png)
