### ISSUE TITLE
Week-Picker

### ISSUE THREAD

**Issue by faboweb** [wholesale-design-system/components#30]
In the preorder recommendations frontend we need this component.

I already started implementing using the design aligned before for the web component.

**Comment by faboweb** [comment]
#32

**Comment by fokusferit** [comment]
@faboweb do you have any update on that ? maybe it is already done :) ?

**Comment by fragsalat** [comment]
As far as I saw it the component isn't working and doesn't look well.

**Comment by fragsalat** [comment]
BTW Where is the design for this component?

**Comment by faboweb** [comment]
@fokusferit This is open as we did not have a UX-Alignment meeting in weeks.

@fragsalat If you figured sth is not working please add a detailed issue for that. Please avoid unconstructive critizism like above. I am always open to take things offline.

The design was aligned with Mehmet and Señor Schluchter before the change to Preact. We can however reopen the design discussion, if you think it dramatically differs from what you think it should look like.

**Comment by faboweb** [comment]
BUG: When you click on it there is an error...

**Comment by myueksel** [comment]
Updated of CW picker... aligned to new spacings and styles (same as the date picker).

Invision:
https://zalando.invisionapp.com/d/main/#/console/10454474/235119440/preview

![cw picker v1](https://cloud.githubusercontent.com/assets/25901307/26345702/fe129c0e-3fa3-11e7-8504-705f19fc3355.png)

**Comment by myueksel** [comment]
please check whether there are magic numbers some where in code.

**Comment by fokusferit** [comment]
I'm closing this as there was a PR which merged it. 
If there are open things, please create a new Issue
