### ISSUE TITLE
WS-Header - Text Title has wrong alignment

### ISSUE THREAD

**Issue by fokusferit** [wholesale-design-system/components#39]
Looks like when you provide only a Text for the Header Component the Title is aligned wrong.

Current:
![screen shot 2017-03-29 at 17 31 43](https://cloud.githubusercontent.com/assets/1215719/24462971/adb4b612-14a5-11e7-950f-3f08ed44a141.png)

Expected:

![screen shot 2017-03-29 at 17 32 02](https://cloud.githubusercontent.com/assets/1215719/24462979/b3f35a6a-14a5-11e7-8345-e6eacc89357d.png)

Might be fix with:
Add `.logo`to class

**Comment by faboweb** [comment]
Maybe obsolete after the redesign.

**Comment by schluchter** [comment]
Agreed. Don't fix now.
