### ISSUE TITLE
Remove the margin override for icons in the week picker

### ISSUE THREAD

**Issue by schluchter** [wholesale-design-system/components#41]
This bad boy needs to go once the icon alignment is fixed more globally.

Location: src/ws-week-picker/ws-week-picker.scss

```scss
i {
    font-size: 1rem;
    //TODO: This overrides a magic-numbers declaration in the SCSS repo's icons.scss Remove once  margin-top -25% hack is removed there.
    &::before {
          margin: 0;
    }
}

**Comment by fragsalat** [comment]
The margin is already removed in the atomic design refactoring

**Comment by fragsalat** [comment]
PS: use ``` instead of ` to have multi line code blocks in github :)

**Comment by schluchter** [comment]
Damn! Awesome.

**Comment by fragsalat** [comment]
Is this still necessary? Mehmet and me checkted the styling of date and week picker.

**Comment by fokusferit** [comment]
Closing it. No response anymore.
