### ISSUE TITLE
Documentation is not clear regarding how to use Demo

### ISSUE THREAD

**Issue by qlibin** [wholesale-design-system/components#46]
It says:

> In 'demo/index.html' you will find already build web-components. And see how you can integrate them in a vanilla setup.

But all that `index.html` has inside is basically import of one non existing script:
```
    <script src="bundle.js"></script>
```

**Comment by fragsalat** [comment]
True, The built components are inside the dist folder and demo should use them

**Comment by faboweb** [comment]
`npm run serve` is also not really working on master -> components produce errors
