### ISSUE TITLE
Usage section of README

### ISSUE THREAD

**Issue by qlibin** [wholesale-design-system/components#47]
Usage section of README says:
> run `gulp` for building / watcher
> `gulp test` for test / watcher 

_I think it's explicitly implied that I have to run also `npm install` (which in my opinion should also be documented)_

After doing following:
```
$ npm install
$ gulp
```

`gulp` fails with following output:
```
[14:42:39] Using gulpfile ~/dev/js/components/gulpfile.js
[14:42:39] Task 'default' is not in your gulpfile
[14:42:39] Please check the documentation for proper gulpfile formatting
```

`gulp test` fails with following:
```
$ gulp test
[14:56:16] Using gulpfile ~/dev/js/components/gulpfile.js
[14:56:16] Starting 'test'...
11 04 2017 14:56:16.849:ERROR [config]: File /Users/alibin/dev/js/components/build/tasks/../../karma.conf.js does not exist!
```

**Comment by fragsalat** [comment]
Either you run `gulp build` to build the components or to run the demo page with react `npm run start` or with preact `npm run start:preact`

**Comment by qlibin** [comment]
Thank you @fragsalat but this doesn't help :(

Both `npm run start` and `npm run start:preact` show the error:
```
ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js!./demo/index.scss
Module build failed: 
      margin-top: $space-l;
                 ^
      Undefined variable: "$space-l".
      in /Users/alibin/dev/js/components/src/ws-header/ws-header.scss (line 230, column 19)
 @ ./demo/index.scss 4:14-117
 @ ./demo/demo_app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./demo/demo_app.js
webpack: Failed to compile.
```

:man_shrugging: 

FYI: my node version is v7.7.4 and npm 4.1.2

**Comment by fragsalat** [comment]
@qlibin Can you pls run `npm i -D https://github.com/wholesale-design-system/scss.git`

I guess the latest master of scss repo isn't installed.

**Comment by qlibin** [comment]
There was one warning during the `npm i -D https://git...`:
```
npm WARN url-loader@0.5.7 requires a peer of file-loader@* but none was installed.
```

But it helped! Thank you
