### ISSUE TITLE
Updated README for preact

### ISSUE THREAD

**Issue by schluchter** [wholesale-design-system/components#9]
The README references the vanilla WebComponents process. Should we update the README with more specific instructions? I would love to try contributing a component as well, but need some pointers to get started. @wholesale-design-system/engineers

**Comment by faboweb** [comment]
👍  feel free to contribute. do you want to get a component assigned?

**Comment by schluchter** [comment]
Yes please :) I need some practice, and an intro into the build process, but that would be really fun.

**Comment by fokusferit** [comment]
@schluchter Any updates on Readme update :D ?
